# Generated by Django 4.0.6 on 2022-08-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_alter_userindo_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userindo',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工资'),
        ),
    ]
